///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TradeTrackerProject.TestCases.LaunchApp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LaunchTradeTrackerAppFirstTime recording.
    /// </summary>
    [TestModule("c030642c-7f0c-4cf0-934f-b77fdbb0af3a", ModuleType.Recording, 1)]
    public partial class LaunchTradeTrackerAppFirstTime : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TradeTrackerProject.TradeTrackerProjectRepository repository.
        /// </summary>
        public static TradeTrackerProject.TradeTrackerProjectRepository repo = TradeTrackerProject.TradeTrackerProjectRepository.Instance;

        static LaunchTradeTrackerAppFirstTime instance = new LaunchTradeTrackerAppFirstTime();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LaunchTradeTrackerAppFirstTime()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LaunchTradeTrackerAppFirstTime Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'pk.com.tradetracker' on device " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + ".", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "pk.com.tradetracker", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='WELCOME') on item 'PkComTradetracker.WELCOME'.", repo.PkComTradetracker.WELCOMEInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.PkComTradetracker.WELCOMEInfo, "Caption", "WELCOME");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.AndroidWidgetImageView' at Center", repo.PkComTradetracker.AndroidWidgetImageViewInfo, new RecordItemIndex(2));
            repo.PkComTradetracker.AndroidWidgetImageView.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'PkComTradetracker'.", repo.PkComTradetracker.SelfInfo, new RecordItemIndex(3));
            repo.PkComTradetracker.Self.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.ButtonSubmit' at Center", repo.PkComTradetracker.ButtonSubmitInfo, new RecordItemIndex(4));
            repo.PkComTradetracker.ButtonSubmit.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='ROUTE LIST') on item 'PkComTradetracker.ROUTELIST'.", repo.PkComTradetracker.ROUTELISTInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.PkComTradetracker.ROUTELISTInfo, "Caption", "ROUTE LIST");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'PkComTradetracker.List.Friday' at Center", repo.PkComTradetracker.List.FridayInfo, new RecordItemIndex(6));
            repo.PkComTradetracker.List.Friday.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
