///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TradeTrackerProject.TestCases.TK_ShopOpen
{
    public partial class BWUMaintenance
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mobile_key_press_PkComTradetracker4(RepoItemInfo mobileappInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'mobileappInfo'.", mobileappInfo);
            mobileappInfo.FindAdapter<MobileApp>().PressKeys("{BACK}");
        }

        public void Touch_ShopOpen_RetailerDidNotAllow(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'containerInfo' at Center", containerInfo);
            containerInfo.FindAdapter<Container>().Touch();
        }

        public void Touch_ShopOpen_TPOSMNotAvailable1(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'containerInfo' at Center", containerInfo);
            containerInfo.FindAdapter<Container>().Touch();
        }

        public void Touch_ShopOpen_FreshDeployment1(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'containerInfo' at Center", containerInfo);
            containerInfo.FindAdapter<Container>().Touch();
        }

        public void Touch_ShopOpen_ValidateOKButton2(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'buttonInfo' at Center", buttonInfo);
            buttonInfo.FindAdapter<Button>().Touch();
        }

        public void Mobile_key_press_PkComTradetracker3(RepoItemInfo mobileappInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'mobileappInfo'.", mobileappInfo);
            mobileappInfo.FindAdapter<MobileApp>().PressKeys("{BACK}");
        }

        public void Touch_ShopOpen_BWUPosterDeployed_No(RepoItemInfo radiobuttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'radiobuttonInfo' at Center", radiobuttonInfo);
            radiobuttonInfo.FindAdapter<RadioButton>().Touch();
        }

        public void Mobile_key_press_PkComTradetracker2(RepoItemInfo mobileappInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'mobileappInfo'.", mobileappInfo);
            mobileappInfo.FindAdapter<MobileApp>().PressKeys("{BACK}");
        }

        public void Touch_ShopOpen_TPOSMNotAvailable(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'containerInfo' at Center", containerInfo);
            containerInfo.FindAdapter<Container>().Touch();
        }

        public void Touch_ShopOpen_FreshDeployment(RepoItemInfo containerInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'containerInfo' at Center", containerInfo);
            containerInfo.FindAdapter<Container>().Touch();
        }

        public void Touch_ShopOpen_ValidateOKButton1(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'buttonInfo' at Center", buttonInfo);
            buttonInfo.FindAdapter<Button>().Touch();
        }

        public void Mobile_key_press_PkComTradetracker1(RepoItemInfo mobileappInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'mobileappInfo'.", mobileappInfo);
            mobileappInfo.FindAdapter<MobileApp>().PressKeys("{BACK}");
        }

        public void Touch_ShopOpen_BWUPosterDeployed_Yes(RepoItemInfo radiobuttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'radiobuttonInfo' at Center", radiobuttonInfo);
            radiobuttonInfo.FindAdapter<RadioButton>().Touch();
        }

        public void Touch_ShopOpen_ValidateOKButton(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'buttonInfo' at Center", buttonInfo);
            buttonInfo.FindAdapter<Button>().Touch();
        }

        public void Mobile_key_press_PkComTradetracker(RepoItemInfo mobileappInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'mobileappInfo'.", mobileappInfo);
            mobileappInfo.FindAdapter<MobileApp>().PressKeys("{BACK}");
        }

    }
}
